export const countries = [
  {
    code1: 'AF',
    code2: 'AFG',
    name: 'Afghanistan',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg',
  },
  { code1: 'AX', code2: 'ALA', name: 'Åland Islands', flag: 'https://flagcdn.com/ax.svg' },
  { code1: 'AL', code2: 'ALB', name: 'Albania', flag: 'https://flagcdn.com/al.svg' },
  { code1: 'DZ', code2: 'DZA', name: 'Algeria', flag: 'https://flagcdn.com/dz.svg' },
  { code1: 'AS', code2: 'ASM', name: 'American Samoa', flag: 'https://flagcdn.com/as.svg' },
  { code1: 'AD', code2: 'AND', name: 'Andorra', flag: 'https://flagcdn.com/ad.svg' },
  { code1: 'AO', code2: 'AGO', name: 'Angola', flag: 'https://flagcdn.com/ao.svg' },
  { code1: 'AI', code2: 'AIA', name: 'Anguilla', flag: 'https://flagcdn.com/ai.svg' },
  { code1: 'AQ', code2: 'ATA', name: 'Antarctica', flag: 'https://flagcdn.com/aq.svg' },
  { code1: 'AG', code2: 'ATG', name: 'Antigua and Barbuda', flag: 'https://flagcdn.com/ag.svg' },
  { code1: 'AR', code2: 'ARG', name: 'Argentina', flag: 'https://flagcdn.com/ar.svg' },
  { code1: 'AM', code2: 'ARM', name: 'Armenia', flag: 'https://flagcdn.com/am.svg' },
  { code1: 'AW', code2: 'ABW', name: 'Aruba', flag: 'https://flagcdn.com/aw.svg' },
  { code1: 'AU', code2: 'AUS', name: 'Australia', flag: 'https://flagcdn.com/au.svg' },
  { code1: 'AT', code2: 'AUT', name: 'Austria', flag: 'https://flagcdn.com/at.svg' },
  { code1: 'AZ', code2: 'AZE', name: 'Azerbaijan', flag: 'https://flagcdn.com/az.svg' },
  { code1: 'BS', code2: 'BHS', name: 'Bahamas', flag: 'https://flagcdn.com/bs.svg' },
  { code1: 'BH', code2: 'BHR', name: 'Bahrain', flag: 'https://flagcdn.com/bh.svg' },
  { code1: 'BD', code2: 'BGD', name: 'Bangladesh', flag: 'https://flagcdn.com/bd.svg' },
  { code1: 'BB', code2: 'BRB', name: 'Barbados', flag: 'https://flagcdn.com/bb.svg' },
  { code1: 'BY', code2: 'BLR', name: 'Belarus', flag: 'https://flagcdn.com/by.svg' },
  { code1: 'BE', code2: 'BEL', name: 'Belgium', flag: 'https://flagcdn.com/be.svg' },
  { code1: 'BZ', code2: 'BLZ', name: 'Belize', flag: 'https://flagcdn.com/bz.svg' },
  { code1: 'BJ', code2: 'BEN', name: 'Benin', flag: 'https://flagcdn.com/bj.svg' },
  { code1: 'BM', code2: 'BMU', name: 'Bermuda', flag: 'https://flagcdn.com/bm.svg' },
  { code1: 'BT', code2: 'BTN', name: 'Bhutan', flag: 'https://flagcdn.com/bt.svg' },
  { code1: 'BO', code2: 'BOL', name: 'Bolivia (Plurinational State of)', flag: 'https://flagcdn.com/bo.svg' },
  { code1: 'BQ', code2: 'BES', name: 'Bonaire, Sint Eustatius and Saba', flag: 'https://flagcdn.com/bq.svg' },
  { code1: 'BA', code2: 'BIH', name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/ba.svg' },
  { code1: 'BW', code2: 'BWA', name: 'Botswana', flag: 'https://flagcdn.com/bw.svg' },
  { code1: 'BV', code2: 'BVT', name: 'Bouvet Island', flag: 'https://flagcdn.com/bv.svg' },
  { code1: 'BR', code2: 'BRA', name: 'Brazil', flag: 'https://flagcdn.com/br.svg' },
  { code1: 'IO', code2: 'IOT', name: 'British Indian Ocean Territory', flag: 'https://flagcdn.com/io.svg' },
  {
    code1: 'UM',
    code2: 'UMI',
    name: 'United States Minor Outlying Islands',
    flag: 'https://flagcdn.com/um.svg',
  },
  { code1: 'VG', code2: 'VGB', name: 'Virgin Islands (British)', flag: 'https://flagcdn.com/vg.svg' },
  { code1: 'VI', code2: 'VIR', name: 'Virgin Islands (U.S.)', flag: 'https://flagcdn.com/vi.svg' },
  { code1: 'BN', code2: 'BRN', name: 'Brunei Darussalam', flag: 'https://flagcdn.com/bn.svg' },
  { code1: 'BG', code2: 'BGR', name: 'Bulgaria', flag: 'https://flagcdn.com/bg.svg' },
  { code1: 'BF', code2: 'BFA', name: 'Burkina Faso', flag: 'https://flagcdn.com/bf.svg' },
  { code1: 'BI', code2: 'BDI', name: 'Burundi', flag: 'https://flagcdn.com/bi.svg' },
  { code1: 'KH', code2: 'KHM', name: 'Cambodia', flag: 'https://flagcdn.com/kh.svg' },
  { code1: 'CM', code2: 'CMR', name: 'Cameroon', flag: 'https://flagcdn.com/cm.svg' },
  { code1: 'CA', code2: 'CAN', name: 'Canada', flag: 'https://flagcdn.com/ca.svg' },
  { code1: 'CV', code2: 'CPV', name: 'Cabo Verde', flag: 'https://flagcdn.com/cv.svg' },
  { code1: 'KY', code2: 'CYM', name: 'Cayman Islands', flag: 'https://flagcdn.com/ky.svg' },
  { code1: 'CF', code2: 'CAF', name: 'Central African Republic', flag: 'https://flagcdn.com/cf.svg' },
  { code1: 'TD', code2: 'TCD', name: 'Chad', flag: 'https://flagcdn.com/td.svg' },
  { code1: 'CL', code2: 'CHL', name: 'Chile', flag: 'https://flagcdn.com/cl.svg' },
  { code1: 'CN', code2: 'CHN', name: 'China', flag: 'https://flagcdn.com/cn.svg' },
  { code1: 'CX', code2: 'CXR', name: 'Christmas Island', flag: 'https://flagcdn.com/cx.svg' },
  { code1: 'CC', code2: 'CCK', name: 'Cocos (Keeling) Islands', flag: 'https://flagcdn.com/cc.svg' },
  { code1: 'CO', code2: 'COL', name: 'Colombia', flag: 'https://flagcdn.com/co.svg' },
  { code1: 'KM', code2: 'COM', name: 'Comoros', flag: 'https://flagcdn.com/km.svg' },
  { code1: 'CG', code2: 'COG', name: 'Congo', flag: 'https://flagcdn.com/cg.svg' },
  { code1: 'CD', code2: 'COD', name: 'Congo (Democratic Republic of the)', flag: 'https://flagcdn.com/cd.svg' },
  { code1: 'CK', code2: 'COK', name: 'Cook Islands', flag: 'https://flagcdn.com/ck.svg' },
  { code1: 'CR', code2: 'CRI', name: 'Costa Rica', flag: 'https://flagcdn.com/cr.svg' },
  { code1: 'HR', code2: 'HRV', name: 'Croatia', flag: 'https://flagcdn.com/hr.svg' },
  { code1: 'CU', code2: 'CUB', name: 'Cuba', flag: 'https://flagcdn.com/cu.svg' },
  { code1: 'CW', code2: 'CUW', name: 'Curaçao', flag: 'https://flagcdn.com/cw.svg' },
  { code1: 'CY', code2: 'CYP', name: 'Cyprus', flag: 'https://flagcdn.com/cy.svg' },
  { code1: 'CZ', code2: 'CZE', name: 'Czech Republic', flag: 'https://flagcdn.com/cz.svg' },
  { code1: 'DK', code2: 'DNK', name: 'Denmark', flag: 'https://flagcdn.com/dk.svg' },
  { code1: 'DJ', code2: 'DJI', name: 'Djibouti', flag: 'https://flagcdn.com/dj.svg' },
  { code1: 'DM', code2: 'DMA', name: 'Dominica', flag: 'https://flagcdn.com/dm.svg' },
  { code1: 'DO', code2: 'DOM', name: 'Dominican Republic', flag: 'https://flagcdn.com/do.svg' },
  { code1: 'EC', code2: 'ECU', name: 'Ecuador', flag: 'https://flagcdn.com/ec.svg' },
  { code1: 'EG', code2: 'EGY', name: 'Egypt', flag: 'https://flagcdn.com/eg.svg' },
  { code1: 'SV', code2: 'SLV', name: 'El Salvador', flag: 'https://flagcdn.com/sv.svg' },
  { code1: 'GQ', code2: 'GNQ', name: 'Equatorial Guinea', flag: 'https://flagcdn.com/gq.svg' },
  { code1: 'ER', code2: 'ERI', name: 'Eritrea', flag: 'https://flagcdn.com/er.svg' },
  { code1: 'EE', code2: 'EST', name: 'Estonia', flag: 'https://flagcdn.com/ee.svg' },
  { code1: 'ET', code2: 'ETH', name: 'Ethiopia', flag: 'https://flagcdn.com/et.svg' },
  { code1: 'FK', code2: 'FLK', name: 'Falkland Islands (Malvinas)', flag: 'https://flagcdn.com/fk.svg' },
  { code1: 'FO', code2: 'FRO', name: 'Faroe Islands', flag: 'https://flagcdn.com/fo.svg' },
  { code1: 'FJ', code2: 'FJI', name: 'Fiji', flag: 'https://flagcdn.com/fj.svg' },
  { code1: 'FI', code2: 'FIN', name: 'Finland', flag: 'https://flagcdn.com/fi.svg' },
  { code1: 'FR', code2: 'FRA', name: 'France', flag: 'https://flagcdn.com/fr.svg' },
  { code1: 'GF', code2: 'GUF', name: 'French Guiana', flag: 'https://flagcdn.com/gf.svg' },
  { code1: 'PF', code2: 'PYF', name: 'French Polynesia', flag: 'https://flagcdn.com/pf.svg' },
  { code1: 'TF', code2: 'ATF', name: 'French Southern Territories', flag: 'https://flagcdn.com/tf.svg' },
  { code1: 'GA', code2: 'GAB', name: 'Gabon', flag: 'https://flagcdn.com/ga.svg' },
  { code1: 'GM', code2: 'GMB', name: 'Gambia', flag: 'https://flagcdn.com/gm.svg' },
  { code1: 'GE', code2: 'GEO', name: 'Georgia', flag: 'https://flagcdn.com/ge.svg' },
  { code1: 'DE', code2: 'DEU', name: 'Germany', flag: 'https://flagcdn.com/de.svg' },
  { code1: 'GH', code2: 'GHA', name: 'Ghana', flag: 'https://flagcdn.com/gh.svg' },
  { code1: 'GI', code2: 'GIB', name: 'Gibraltar', flag: 'https://flagcdn.com/gi.svg' },
  { code1: 'GR', code2: 'GRC', name: 'Greece', flag: 'https://flagcdn.com/gr.svg' },
  { code1: 'GL', code2: 'GRL', name: 'Greenland', flag: 'https://flagcdn.com/gl.svg' },
  { code1: 'GD', code2: 'GRD', name: 'Grenada', flag: 'https://flagcdn.com/gd.svg' },
  { code1: 'GP', code2: 'GLP', name: 'Guadeloupe', flag: 'https://flagcdn.com/gp.svg' },
  { code1: 'GU', code2: 'GUM', name: 'Guam', flag: 'https://flagcdn.com/gu.svg' },
  { code1: 'GT', code2: 'GTM', name: 'Guatemala', flag: 'https://flagcdn.com/gt.svg' },
  { code1: 'GG', code2: 'GGY', name: 'Guernsey', flag: 'https://flagcdn.com/gg.svg' },
  { code1: 'GN', code2: 'GIN', name: 'Guinea', flag: 'https://flagcdn.com/gn.svg' },
  { code1: 'GW', code2: 'GNB', name: 'Guinea-Bissau', flag: 'https://flagcdn.com/gw.svg' },
  { code1: 'GY', code2: 'GUY', name: 'Guyana', flag: 'https://flagcdn.com/gy.svg' },
  { code1: 'HT', code2: 'HTI', name: 'Haiti', flag: 'https://flagcdn.com/ht.svg' },
  { code1: 'HM', code2: 'HMD', name: 'Heard Island and McDonald Islands', flag: 'https://flagcdn.com/hm.svg' },
  { code1: 'VA', code2: 'VAT', name: 'Vatican City', flag: 'https://flagcdn.com/va.svg' },
  { code1: 'HN', code2: 'HND', name: 'Honduras', flag: 'https://flagcdn.com/hn.svg' },
  { code1: 'HU', code2: 'HUN', name: 'Hungary', flag: 'https://flagcdn.com/hu.svg' },
  { code1: 'HK', code2: 'HKG', name: 'Hong Kong', flag: 'https://flagcdn.com/hk.svg' },
  { code1: 'IS', code2: 'ISL', name: 'Iceland', flag: 'https://flagcdn.com/is.svg' },
  { code1: 'IN', code2: 'IND', name: 'India', flag: 'https://flagcdn.com/in.svg' },
  { code1: 'ID', code2: 'IDN', name: 'Indonesia', flag: 'https://flagcdn.com/id.svg' },
  { code1: 'CI', code2: 'CIV', name: 'Ivory Coast', flag: 'https://flagcdn.com/ci.svg' },
  { code1: 'IR', code2: 'IRN', name: 'Iran (Islamic Republic of)', flag: 'https://flagcdn.com/ir.svg' },
  { code1: 'IQ', code2: 'IRQ', name: 'Iraq', flag: 'https://flagcdn.com/iq.svg' },
  { code1: 'IE', code2: 'IRL', name: 'Ireland', flag: 'https://flagcdn.com/ie.svg' },
  { code1: 'IM', code2: 'IMN', name: 'Isle of Man', flag: 'https://flagcdn.com/im.svg' },
  { code1: 'IL', code2: 'ISR', name: 'Israel', flag: 'https://flagcdn.com/il.svg' },
  { code1: 'IT', code2: 'ITA', name: 'Italy', flag: 'https://flagcdn.com/it.svg' },
  { code1: 'JM', code2: 'JAM', name: 'Jamaica', flag: 'https://flagcdn.com/jm.svg' },
  { code1: 'JP', code2: 'JPN', name: 'Japan', flag: 'https://flagcdn.com/jp.svg' },
  { code1: 'JE', code2: 'JEY', name: 'Jersey', flag: 'https://flagcdn.com/je.svg' },
  { code1: 'JO', code2: 'JOR', name: 'Jordan', flag: 'https://flagcdn.com/jo.svg' },
  { code1: 'KZ', code2: 'KAZ', name: 'Kazakhstan', flag: 'https://flagcdn.com/kz.svg' },
  { code1: 'KE', code2: 'KEN', name: 'Kenya', flag: 'https://flagcdn.com/ke.svg' },
  { code1: 'KI', code2: 'KIR', name: 'Kiribati', flag: 'https://flagcdn.com/ki.svg' },
  { code1: 'KW', code2: 'KWT', name: 'Kuwait', flag: 'https://flagcdn.com/kw.svg' },
  { code1: 'KG', code2: 'KGZ', name: 'Kyrgyzstan', flag: 'https://flagcdn.com/kg.svg' },
  { code1: 'LA', code2: 'LAO', name: "Lao People's Democratic Republic", flag: 'https://flagcdn.com/la.svg' },
  { code1: 'LV', code2: 'LVA', name: 'Latvia', flag: 'https://flagcdn.com/lv.svg' },
  { code1: 'LB', code2: 'LBN', name: 'Lebanon', flag: 'https://flagcdn.com/lb.svg' },
  { code1: 'LS', code2: 'LSO', name: 'Lesotho', flag: 'https://flagcdn.com/ls.svg' },
  { code1: 'LR', code2: 'LBR', name: 'Liberia', flag: 'https://flagcdn.com/lr.svg' },
  { code1: 'LY', code2: 'LBY', name: 'Libya', flag: 'https://flagcdn.com/ly.svg' },
  { code1: 'LI', code2: 'LIE', name: 'Liechtenstein', flag: 'https://flagcdn.com/li.svg' },
  { code1: 'LT', code2: 'LTU', name: 'Lithuania', flag: 'https://flagcdn.com/lt.svg' },
  { code1: 'LU', code2: 'LUX', name: 'Luxembourg', flag: 'https://flagcdn.com/lu.svg' },
  { code1: 'MO', code2: 'MAC', name: 'Macao', flag: 'https://flagcdn.com/mo.svg' },
  { code1: 'MK', code2: 'MKD', name: 'North Macedonia', flag: 'https://flagcdn.com/mk.svg' },
  { code1: 'MG', code2: 'MDG', name: 'Madagascar', flag: 'https://flagcdn.com/mg.svg' },
  { code1: 'MW', code2: 'MWI', name: 'Malawi', flag: 'https://flagcdn.com/mw.svg' },
  { code1: 'MY', code2: 'MYS', name: 'Malaysia', flag: 'https://flagcdn.com/my.svg' },
  { code1: 'MV', code2: 'MDV', name: 'Maldives', flag: 'https://flagcdn.com/mv.svg' },
  { code1: 'ML', code2: 'MLI', name: 'Mali', flag: 'https://flagcdn.com/ml.svg' },
  { code1: 'MT', code2: 'MLT', name: 'Malta', flag: 'https://flagcdn.com/mt.svg' },
  { code1: 'MH', code2: 'MHL', name: 'Marshall Islands', flag: 'https://flagcdn.com/mh.svg' },
  { code1: 'MQ', code2: 'MTQ', name: 'Martinique', flag: 'https://flagcdn.com/mq.svg' },
  { code1: 'MR', code2: 'MRT', name: 'Mauritania', flag: 'https://flagcdn.com/mr.svg' },
  { code1: 'MU', code2: 'MUS', name: 'Mauritius', flag: 'https://flagcdn.com/mu.svg' },
  { code1: 'YT', code2: 'MYT', name: 'Mayotte', flag: 'https://flagcdn.com/yt.svg' },
  { code1: 'MX', code2: 'MEX', name: 'Mexico', flag: 'https://flagcdn.com/mx.svg' },
  { code1: 'FM', code2: 'FSM', name: 'Micronesia (Federated States of)', flag: 'https://flagcdn.com/fm.svg' },
  { code1: 'MD', code2: 'MDA', name: 'Moldova (Republic of)', flag: 'https://flagcdn.com/md.svg' },
  { code1: 'MC', code2: 'MCO', name: 'Monaco', flag: 'https://flagcdn.com/mc.svg' },
  { code1: 'MN', code2: 'MNG', name: 'Mongolia', flag: 'https://flagcdn.com/mn.svg' },
  { code1: 'ME', code2: 'MNE', name: 'Montenegro', flag: 'https://flagcdn.com/me.svg' },
  { code1: 'MS', code2: 'MSR', name: 'Montserrat', flag: 'https://flagcdn.com/ms.svg' },
  { code1: 'MA', code2: 'MAR', name: 'Morocco', flag: 'https://flagcdn.com/ma.svg' },
  { code1: 'MZ', code2: 'MOZ', name: 'Mozambique', flag: 'https://flagcdn.com/mz.svg' },
  { code1: 'MM', code2: 'MMR', name: 'Myanmar', flag: 'https://flagcdn.com/mm.svg' },
  { code1: 'NA', code2: 'NAM', name: 'Namibia', flag: 'https://flagcdn.com/na.svg' },
  { code1: 'NR', code2: 'NRU', name: 'Nauru', flag: 'https://flagcdn.com/nr.svg' },
  { code1: 'NP', code2: 'NPL', name: 'Nepal', flag: 'https://flagcdn.com/np.svg' },
  { code1: 'NL', code2: 'NLD', name: 'Netherlands', flag: 'https://flagcdn.com/nl.svg' },
  { code1: 'NC', code2: 'NCL', name: 'New Caledonia', flag: 'https://flagcdn.com/nc.svg' },
  { code1: 'NZ', code2: 'NZL', name: 'New Zealand', flag: 'https://flagcdn.com/nz.svg' },
  { code1: 'NI', code2: 'NIC', name: 'Nicaragua', flag: 'https://flagcdn.com/ni.svg' },
  { code1: 'NE', code2: 'NER', name: 'Niger', flag: 'https://flagcdn.com/ne.svg' },
  { code1: 'NG', code2: 'NGA', name: 'Nigeria', flag: 'https://flagcdn.com/ng.svg' },
  { code1: 'NU', code2: 'NIU', name: 'Niue', flag: 'https://flagcdn.com/nu.svg' },
  { code1: 'NF', code2: 'NFK', name: 'Norfolk Island', flag: 'https://flagcdn.com/nf.svg' },
  {
    code1: 'KP',
    code2: 'PRK',
    name: "Korea (Democratic People's Republic of)",
    flag: 'https://flagcdn.com/kp.svg',
  },
  { code1: 'MP', code2: 'MNP', name: 'Northern Mariana Islands', flag: 'https://flagcdn.com/mp.svg' },
  { code1: 'NO', code2: 'NOR', name: 'Norway', flag: 'https://flagcdn.com/no.svg' },
  { code1: 'OM', code2: 'OMN', name: 'Oman', flag: 'https://flagcdn.com/om.svg' },
  { code1: 'PK', code2: 'PAK', name: 'Pakistan', flag: 'https://flagcdn.com/pk.svg' },
  { code1: 'PW', code2: 'PLW', name: 'Palau', flag: 'https://flagcdn.com/pw.svg' },
  { code1: 'PS', code2: 'PSE', name: 'Palestine, State of', flag: 'https://flagcdn.com/ps.svg' },
  { code1: 'PA', code2: 'PAN', name: 'Panama', flag: 'https://flagcdn.com/pa.svg' },
  { code1: 'PG', code2: 'PNG', name: 'Papua New Guinea', flag: 'https://flagcdn.com/pg.svg' },
  { code1: 'PY', code2: 'PRY', name: 'Paraguay', flag: 'https://flagcdn.com/py.svg' },
  { code1: 'PE', code2: 'PER', name: 'Peru', flag: 'https://flagcdn.com/pe.svg' },
  { code1: 'PH', code2: 'PHL', name: 'Philippines', flag: 'https://flagcdn.com/ph.svg' },
  { code1: 'PN', code2: 'PCN', name: 'Pitcairn', flag: 'https://flagcdn.com/pn.svg' },
  { code1: 'PL', code2: 'POL', name: 'Poland', flag: 'https://flagcdn.com/pl.svg' },
  { code1: 'PT', code2: 'PRT', name: 'Portugal', flag: 'https://flagcdn.com/pt.svg' },
  { code1: 'PR', code2: 'PRI', name: 'Puerto Rico', flag: 'https://flagcdn.com/pr.svg' },
  { code1: 'QA', code2: 'QAT', name: 'Qatar', flag: 'https://flagcdn.com/qa.svg' },
  { code1: 'XK', code2: 'UNK', name: 'Republic of Kosovo', flag: 'https://flagcdn.com/xk.svg' },
  { code1: 'RE', code2: 'REU', name: 'Réunion', flag: 'https://flagcdn.com/re.svg' },
  { code1: 'RO', code2: 'ROU', name: 'Romania', flag: 'https://flagcdn.com/ro.svg' },
  { code1: 'RU', code2: 'RUS', name: 'Russian Federation', flag: 'https://flagcdn.com/ru.svg' },
  { code1: 'RW', code2: 'RWA', name: 'Rwanda', flag: 'https://flagcdn.com/rw.svg' },
  { code1: 'BL', code2: 'BLM', name: 'Saint Barthélemy', flag: 'https://flagcdn.com/bl.svg' },
  {
    code1: 'SH',
    code2: 'SHN',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    flag: 'https://flagcdn.com/sh.svg',
  },
  { code1: 'KN', code2: 'KNA', name: 'Saint Kitts and Nevis', flag: 'https://flagcdn.com/kn.svg' },
  { code1: 'LC', code2: 'LCA', name: 'Saint Lucia', flag: 'https://flagcdn.com/lc.svg' },
  { code1: 'MF', code2: 'MAF', name: 'Saint Martin (French part)', flag: 'https://flagcdn.com/mf.svg' },
  { code1: 'PM', code2: 'SPM', name: 'Saint Pierre and Miquelon', flag: 'https://flagcdn.com/pm.svg' },
  { code1: 'VC', code2: 'VCT', name: 'Saint Vincent and the Grenadines', flag: 'https://flagcdn.com/vc.svg' },
  { code1: 'WS', code2: 'WSM', name: 'Samoa', flag: 'https://flagcdn.com/ws.svg' },
  { code1: 'SM', code2: 'SMR', name: 'San Marino', flag: 'https://flagcdn.com/sm.svg' },
  { code1: 'ST', code2: 'STP', name: 'Sao Tome and Principe', flag: 'https://flagcdn.com/st.svg' },
  { code1: 'SA', code2: 'SAU', name: 'Saudi Arabia', flag: 'https://flagcdn.com/sa.svg' },
  { code1: 'SN', code2: 'SEN', name: 'Senegal', flag: 'https://flagcdn.com/sn.svg' },
  { code1: 'RS', code2: 'SRB', name: 'Serbia', flag: 'https://flagcdn.com/rs.svg' },
  { code1: 'SC', code2: 'SYC', name: 'Seychelles', flag: 'https://flagcdn.com/sc.svg' },
  { code1: 'SL', code2: 'SLE', name: 'Sierra Leone', flag: 'https://flagcdn.com/sl.svg' },
  { code1: 'SG', code2: 'SGP', name: 'Singapore', flag: 'https://flagcdn.com/sg.svg' },
  { code1: 'SX', code2: 'SXM', name: 'Sint Maarten (Dutch part)', flag: 'https://flagcdn.com/sx.svg' },
  { code1: 'SK', code2: 'SVK', name: 'Slovakia', flag: 'https://flagcdn.com/sk.svg' },
  { code1: 'SI', code2: 'SVN', name: 'Slovenia', flag: 'https://flagcdn.com/si.svg' },
  { code1: 'SB', code2: 'SLB', name: 'Solomon Islands', flag: 'https://flagcdn.com/sb.svg' },
  { code1: 'SO', code2: 'SOM', name: 'Somalia', flag: 'https://flagcdn.com/so.svg' },
  { code1: 'ZA', code2: 'ZAF', name: 'South Africa', flag: 'https://flagcdn.com/za.svg' },
  {
    code1: 'GS',
    code2: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    flag: 'https://flagcdn.com/gs.svg',
  },
  { code1: 'KR', code2: 'KOR', name: 'Korea (Republic of)', flag: 'https://flagcdn.com/kr.svg' },
  { code1: 'ES', code2: 'ESP', name: 'Spain', flag: 'https://flagcdn.com/es.svg' },
  { code1: 'LK', code2: 'LKA', name: 'Sri Lanka', flag: 'https://flagcdn.com/lk.svg' },
  { code1: 'SD', code2: 'SDN', name: 'Sudan', flag: 'https://flagcdn.com/sd.svg' },
  { code1: 'SS', code2: 'SSD', name: 'South Sudan', flag: 'https://flagcdn.com/ss.svg' },
  { code1: 'SR', code2: 'SUR', name: 'Suriname', flag: 'https://flagcdn.com/sr.svg' },
  { code1: 'SJ', code2: 'SJM', name: 'Svalbard and Jan Mayen', flag: 'https://flagcdn.com/sj.svg' },
  { code1: 'SZ', code2: 'SWZ', name: 'Swaziland', flag: 'https://flagcdn.com/sz.svg' },
  { code1: 'SE', code2: 'SWE', name: 'Sweden', flag: 'https://flagcdn.com/se.svg' },
  { code1: 'CH', code2: 'CHE', name: 'Switzerland', flag: 'https://flagcdn.com/ch.svg' },
  { code1: 'SY', code2: 'SYR', name: 'Syrian Arab Republic', flag: 'https://flagcdn.com/sy.svg' },
  { code1: 'TW', code2: 'TWN', name: 'Taiwan', flag: 'https://flagcdn.com/tw.svg' },
  { code1: 'TJ', code2: 'TJK', name: 'Tajikistan', flag: 'https://flagcdn.com/tj.svg' },
  { code1: 'TZ', code2: 'TZA', name: 'Tanzania, United Republic of', flag: 'https://flagcdn.com/tz.svg' },
  { code1: 'TH', code2: 'THA', name: 'Thailand', flag: 'https://flagcdn.com/th.svg' },
  { code1: 'TL', code2: 'TLS', name: 'Timor-Leste', flag: 'https://flagcdn.com/tl.svg' },
  { code1: 'TG', code2: 'TGO', name: 'Togo', flag: 'https://flagcdn.com/tg.svg' },
  { code1: 'TK', code2: 'TKL', name: 'Tokelau', flag: 'https://flagcdn.com/tk.svg' },
  { code1: 'TO', code2: 'TON', name: 'Tonga', flag: 'https://flagcdn.com/to.svg' },
  { code1: 'TT', code2: 'TTO', name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/tt.svg' },
  { code1: 'TN', code2: 'TUN', name: 'Tunisia', flag: 'https://flagcdn.com/tn.svg' },
  { code1: 'TR', code2: 'TUR', name: 'Turkey', flag: 'https://flagcdn.com/tr.svg' },
  { code1: 'TM', code2: 'TKM', name: 'Turkmenistan', flag: 'https://flagcdn.com/tm.svg' },
  { code1: 'TC', code2: 'TCA', name: 'Turks and Caicos Islands', flag: 'https://flagcdn.com/tc.svg' },
  { code1: 'TV', code2: 'TUV', name: 'Tuvalu', flag: 'https://flagcdn.com/tv.svg' },
  { code1: 'UG', code2: 'UGA', name: 'Uganda', flag: 'https://flagcdn.com/ug.svg' },
  { code1: 'UA', code2: 'UKR', name: 'Ukraine', flag: 'https://flagcdn.com/ua.svg' },
  { code1: 'AE', code2: 'ARE', name: 'United Arab Emirates', flag: 'https://flagcdn.com/ae.svg' },
  {
    code1: 'GB',
    code2: 'GBR',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    flag: 'https://flagcdn.com/gb.svg',
  },
  { code1: 'US', code2: 'USA', name: 'United States of America', flag: 'https://flagcdn.com/us.svg' },
  { code1: 'UY', code2: 'URY', name: 'Uruguay', flag: 'https://flagcdn.com/uy.svg' },
  { code1: 'UZ', code2: 'UZB', name: 'Uzbekistan', flag: 'https://flagcdn.com/uz.svg' },
  { code1: 'VU', code2: 'VUT', name: 'Vanuatu', flag: 'https://flagcdn.com/vu.svg' },
  { code1: 'VE', code2: 'VEN', name: 'Venezuela (Bolivarian Republic of)', flag: 'https://flagcdn.com/ve.svg' },
  { code1: 'VN', code2: 'VNM', name: 'Vietnam', flag: 'https://flagcdn.com/vn.svg' },
  { code1: 'WF', code2: 'WLF', name: 'Wallis and Futuna', flag: 'https://flagcdn.com/wf.svg' },
  { code1: 'EH', code2: 'ESH', name: 'Western Sahara', flag: 'https://flagcdn.com/eh.svg' },
  { code1: 'YE', code2: 'YEM', name: 'Yemen', flag: 'https://flagcdn.com/ye.svg' },
  { code1: 'ZM', code2: 'ZMB', name: 'Zambia', flag: 'https://flagcdn.com/zm.svg' },
  { code1: 'ZW', code2: 'ZWE', name: 'Zimbabwe', flag: 'https://flagcdn.com/zw.svg' },
];
